### PR TITLE
Added script to update types

### PR DESCRIPTION
**Pull request by matiasbavera**
## What's new
As the title says I added script to update types.

HTH.

### CODE REVIEW

**Comment by koonpeng** [comment]
should we integrate this into the npm scripts instead? clone the repositories on npm postinstall and use colcon for npm build.

**Comment by matiasbavera** [comment]
Sounds good, I'll do that.

**Comment by matiasbavera** [comment]
Hi @koonpeng, there is a couple of things here that I'll like to discuss:
* npm install needs ros2, so this script cannot be a `postinstall`.
* Instead of creating having the colcon_ws folder on the home, I'm now creating it inside of the project folder so it can be independent of the system host's structure.
* I created 3 scripts now:
1) build-prepare: that creates a `colcon_ws`, clone new repos, and copy the romi-js-core-interfaces in `colcon_ws/src/romi-js-core-interfaces`. 
2) build-project: creates the Colcon workspace and build the project.
3) compress: prepare a tar and zip file with the number of the current version of the package.json

The weird things about this approach are the following: 
* The in package.json handles two levels of scripts: (1) Script to be executed in the root of the project (the 3 mentioned above) and the other to be executed on `colcon_ws/src/romi-js-core-interfaces/`.
* We must work on the project root folder and the built project will be in another folder. 


Before these changes if someone wanted to contribute to the project needed to follow this steps:
1. create a `colcon_ws`
2. create a `src/` folder
3. clone the 3 repos including this project.

So the first script that I created was for this case, to handle external dependencies (if we can call it this way). But we will not have that script unless we already clone the project (the egg and the chicken).

**Comment by matiasbavera** [comment]
At least this will help for CI too

**Comment by koonpeng** [comment]
how about the following npm scripts:

sync: creates `colcon_ws`, git clone/pull the latest branch
build: `cd colcon_ws && colcon build <list of targets> && . install/setup.bash && <other tasks>...`

or move everything to colcon

sync: creates `colcon_ws`, git clone/pull the latest branch, symlink package root to `colcon_ws/src`
build: `cd colcon_ws && colcon build <target>`, the CMakeLists will use custom actions to run js tasks, colcon takes care of dependencies.

Can we use `npm pack` to create an archive?

**Comment by matiasbavera** [comment]
> sync: creates colcon_ws, git clone/pull the latest changes, symlink package root to colcon_ws/src
build: cd colcon_ws && colcon build <target>, the CMakeLists will use custom actions to run js tasks, colcon takes care of dependencies.

Thanks for the help @koonpeng , I Implemented the second option. There is a couple of situations though,

1. It seems like `colcon build` is calling `npm install` so I cannot add a preinstall option with `colcon build` because it enters in an infinite loop.

2. I cannot add `colcon build` in `npm build` command because  `colcon build` is calling `npm install`  and `npm install` calls by definition to `npm build` and we will have the same infinite loop situation. src: https://docs.npmjs.com/cli/build. It should be a way for `npm install` not to call `npm build` I don't think it will be a recommended way of doing things though.

3. To solve those problems mentioned above I added an NPM script 
`> "build:colcon": "cd colcon_ws && colcon build"`.
 
So the order of the execution of commands should be like this: 
`> npm run sync`
`> npm run build:colcon` (we can change the name of this)

What do you think about this?

> Can we use npm pack to create an archive?

Yes we can

**Comment by matiasbavera** [comment]
Is it ok to have those script on `.sh` format or is it better to transform it to js node (or ts-node) scripts?

**Comment by koonpeng** [comment]
Given that they would require rmf/ros2 and there is no plans atm to support other platforms, I don't mind them being `.sh`.

The CMakeLists now is just wrapping `npm install`, if we want to go with option 2, all the build instructions should be in cmake side. `npm run build` would just call cmake, cmake then runs python, tsc, webpack, etc to generate and build the project.

**Comment by koonpeng** [comment]
something to note:

we are closing to an official release of rmf, with deb packages hosted somewhere. When that happens, it might be better to build with the system installed packages, ensuring those packages are installed is probably outside the scope of the build steps, it can be considered external dependencies.

**Comment by matiasbavera** [comment]
Solved in  #13

**Pull request closed without merging**
